//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWP22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class function
    {
        public int function_id { get; set; }
        public string function_name { get; set; }
        public string function_icon { get; set; }
    }
}
