//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWP22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class offer
    {
        public int offer_id { get; set; }
        public string offer_name { get; set; }
        public string offer_description { get; set; }
        public string offer_imageurl { get; set; }
    }
}
